# Generated by Django 5.0 on 2024-01-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('contactNumber', models.IntegerField()),
                ('deliveryAddress', models.CharField(max_length=60)),
                ('cylinderType', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
