# Generated by Django 5.0 on 2024-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0002_booking_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cylinderType',
            field=models.CharField(max_length=30),
        ),
    ]
