# Generated by Django 5.0 on 2024-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0008_alter_employees_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('delivery_staff', 'Delivery_staff'), ('office_staff', 'Office_staff')], default='manager', max_length=30),
        ),
    ]
