# Generated by Django 5.0 on 2024-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0009_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('delivery_staff', 'Delivery Staff'), ('office_staff', 'Office Staff')], default='manager', max_length=30),
        ),
    ]
