# Generated by Django 5.0 on 2024-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_booking', '0010_alter_employees_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('document', models.CharField(max_length=50)),
            ],
        ),
    ]
